"use client";
import Link from "next/link";
import type { ReactNode } from "react";
import { ChevronDown, Menu, X } from "lucide-react";
import { cn } from "@lib/utils";
import { Button } from "@components/ui/Button";

export type NavigationLink = { label: string; href: string; description?: string };
export function NavigationItem({ item, className, onNavigate }: { item: NavigationLink; className?: string; onNavigate?: () => void }) { return <Link href={item.href} onClick={onNavigate} className={cn("text-sm font-medium text-slate-700 transition hover:text-sky-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500", className)}>{item.label}</Link>; }
export function DesktopMenu({ items, className }: { items: NavigationLink[]; className?: string }) { return <nav aria-label="Primary navigation" className={cn("hidden items-center gap-6 md:flex", className)}>{items.map((item) => <NavigationItem key={item.href} item={item} />)}</nav>; }
export function MobileMenu({ open, onClose, items, className }: { open: boolean; onClose: () => void; items: NavigationLink[]; className?: string }) { if (!open) return null; return <nav aria-label="Mobile navigation" className={cn("border-t border-slate-200 bg-white p-4 md:hidden", className)}>{items.map((item) => <NavigationItem key={item.href} item={item} onNavigate={onClose} className="block rounded-xl px-3 py-3 hover:bg-slate-50" />)}</nav>; }
export function NavigationToggle({ open, onClick }: { open: boolean; onClick: () => void }) { return <Button variant="outline" size="icon" className="md:hidden" aria-label="Toggle navigation" aria-expanded={open} onClick={onClick}>{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</Button>; }
export function Dropdown({ label, items }: { label: string; items: NavigationLink[] }) { return <details className="group relative"><summary className="flex cursor-pointer list-none items-center gap-1 text-sm font-medium text-slate-700 hover:text-sky-700">{label}<ChevronDown className="h-4 w-4 group-open:rotate-180" /></summary><div className="absolute left-0 top-7 z-50 w-56 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl">{items.map((item) => <NavigationItem key={item.href} item={item} className="block rounded-xl px-3 py-2 hover:bg-slate-50" />)}</div></details>; }
export function MegaMenuPlaceholder({ label, children }: { label: string; children?: ReactNode }) { return <details className="group relative"><summary className="flex cursor-pointer list-none items-center gap-1 text-sm font-medium text-slate-700">{label}<ChevronDown className="h-4 w-4" /></summary><div className="absolute left-0 top-7 z-50 w-[min(42rem,90vw)] rounded-2xl border border-slate-200 bg-white p-6 shadow-xl">{children || <p className="text-sm text-slate-500">Mega menu content will be configured here.</p>}</div></details>; }
export function Breadcrumb({ items }: { items: NavigationLink[] }) { return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap items-center gap-2 text-sm text-slate-500">{items.map((item, index) => <li key={item.href} className="flex items-center gap-2">{index > 0 && <span aria-hidden="true">/</span>}{index === items.length - 1 ? <span aria-current="page" className="font-medium text-slate-700">{item.label}</span> : <Link href={item.href} className="hover:text-sky-700">{item.label}</Link>}</li>)}</ol></nav>; }
export function NavigationGroup({ label, children }: { label?: string; children: ReactNode }) { return <div>{label && <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p>}<div className="space-y-1">{children}</div></div>; }
export function StickyNavigation({ children, className }: { children: ReactNode; className?: string }) { return <header className={cn("sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur", className)}>{children}</header>; }
