"use client";

import type { ReactNode } from "react";
import { ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";
import { cn } from "@lib/utils";
import { Button } from "./Button";

export type Column<T> = { key: keyof T & string; header: ReactNode; render?: (value: T[keyof T], row: T) => ReactNode; className?: string };
export function Table<T extends Record<string, unknown>>({ columns, data, caption }: { columns: Column<T>[]; data: T[]; caption?: string }) { return <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[600px] text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-slate-50 text-slate-600"><tr>{columns.map((column) => <th key={column.key} scope="col" className={cn("px-4 py-3 font-semibold", column.className)}>{column.header}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 bg-white">{data.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column.key} className={cn("px-4 py-3 text-slate-700", column.className)}>{column.render ? column.render(row[column.key], row) : String(row[column.key] ?? "")}</td>)}</tr>)}</tbody></table></div>; }
export const ResponsiveTable = Table;
export function Pagination({ page, totalPages, onPageChange }: { page: number; totalPages: number; onPageChange?: (page: number) => void }) { return <nav aria-label="Pagination" className="flex items-center justify-between gap-3"><Button variant="outline" size="sm" disabled={page <= 1} onClick={() => onPageChange?.(page - 1)} leftIcon={<ChevronLeft className="h-4 w-4" />}>Previous</Button><span className="text-sm text-slate-600">Page {page} of {totalPages}</span><Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => onPageChange?.(page + 1)} rightIcon={<ChevronRight className="h-4 w-4" />}>Next</Button></nav>; }
export function DataList({ items }: { items: Array<{ label: ReactNode; value: ReactNode }> }) { return <dl className="divide-y divide-slate-200">{items.map((item, index) => <div key={index} className="flex justify-between gap-6 py-3"><dt className="text-sm text-slate-600">{item.label}</dt><dd className="text-right text-sm font-medium text-slate-950">{item.value}</dd></div>)}</dl>; }
export const Statistics = DataList;
export function ChartPlaceholder({ title = "Chart", className }: { title?: string; className?: string }) { return <div role="img" aria-label={`${title} chart placeholder`} className={cn("flex min-h-56 items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 text-sm text-slate-500", className)}>{title} chart</div>; }
export function Timeline({ items }: { items: Array<{ title: string; description?: string; time?: string; icon?: ReactNode }> }) { return <ol className="relative ml-2 border-l border-slate-200">{items.map((item, index) => <li key={index} className="relative pb-7 pl-6 last:pb-0"><span className="absolute -left-2.5 top-0 flex h-5 w-5 items-center justify-center rounded-full bg-sky-600 text-white">{item.icon}</span><p className="font-medium text-slate-950">{item.title}</p>{item.time && <time className="text-xs text-slate-500">{item.time}</time>}{item.description && <p className="mt-1 text-sm leading-6 text-slate-600">{item.description}</p>}</li>)}</ol>; }
export function Accordion({ items }: { items: Array<{ title: string; content: ReactNode; defaultOpen?: boolean }> }) { return <div className="divide-y divide-slate-200 rounded-2xl border border-slate-200">{items.map((item, index) => <details key={index} className="group p-4" open={item.defaultOpen}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-slate-950">{item.title}<ChevronDown className="h-5 w-5 text-slate-500 transition group-open:rotate-180" /></summary><div className="pt-3 text-sm leading-6 text-slate-600">{item.content}</div></details>)}</div>; }
export function Tabs({ tabs, activeTab, onChange }: { tabs: Array<{ id: string; label: string; content: ReactNode }>; activeTab?: string; onChange?: (id: string) => void }) { const current = activeTab || tabs[0]?.id; const active = tabs.find((tab) => tab.id === current); return <div><div role="tablist" className="flex gap-1 overflow-x-auto border-b border-slate-200">{tabs.map((tab) => <button key={tab.id} role="tab" aria-selected={current === tab.id} onClick={() => onChange?.(tab.id)} className={cn("whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium", current === tab.id ? "border-sky-600 text-sky-700" : "border-transparent text-slate-600 hover:text-slate-950")}>{tab.label}</button>)}</div><div role="tabpanel" className="pt-5">{active?.content}</div></div>; }
export function Collapsible({ title, children, defaultOpen = false }: { title: string; children: ReactNode; defaultOpen?: boolean }) { return <details open={defaultOpen} className="rounded-2xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold text-slate-950">{title}</summary><div className="pt-3 text-sm text-slate-600">{children}</div></details>; }
