import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { AlertCircle, CheckCircle2, Info, Loader2, WifiOff, Wrench } from "lucide-react";
import { cn } from "@lib/utils";

export type Status = "info" | "success" | "warning" | "error" | "neutral";
const statusStyles: Record<Status, string> = { info: "bg-sky-50 text-sky-800 ring-sky-200", success: "bg-emerald-50 text-emerald-800 ring-emerald-200", warning: "bg-amber-50 text-amber-900 ring-amber-200", error: "bg-red-50 text-red-800 ring-red-200", neutral: "bg-slate-100 text-slate-700 ring-slate-200" };
export function Alert({ status = "info", className, title, children, ...props }: ComponentPropsWithoutRef<"div"> & { status?: Status; title?: string }) { return <div role="alert" className={cn("rounded-2xl px-4 py-3 ring-1", statusStyles[status], className)} {...props}>{title && <p className="font-semibold">{title}</p>}{children && <div className={title ? "mt-1 text-sm" : "text-sm"}>{children}</div>}</div>; }
export const Toast = Alert;
export const Snackbar = Alert;
export function LoadingSpinner({ className, label = "Loading" }: { className?: string; label?: string }) { return <span role="status" className={cn("inline-flex items-center gap-2 text-sm text-slate-600", className)}><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin" /><span className="sr-only">{label}</span></span>; }
export function Skeleton({ className, ...props }: ComponentPropsWithoutRef<"div">) { return <div aria-hidden="true" className={cn("animate-pulse rounded-xl bg-slate-200", className)} {...props} />; }
export function ProgressBar({ value, className, label }: { value: number; className?: string; label?: string }) { const safeValue = Math.max(0, Math.min(100, value)); return <div className={className}><div className="mb-1 flex justify-between text-sm text-slate-600"><span>{label}</span><span>{safeValue}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-sky-600 transition-all" style={{ width: `${safeValue}%` }} /></div></div>; }
export function StatusBadge({ status = "neutral", className, children }: { status?: Status; className?: string; children: ReactNode }) { return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", statusStyles[status], className)}>{children}</span>; }
export function NotificationBadge({ count, className }: { count: number; className?: string }) { return <span aria-label={`${count} notifications`} className={cn("inline-flex min-w-5 items-center justify-center rounded-full bg-red-600 px-1.5 py-0.5 text-xs font-semibold text-white", className)}>{count > 99 ? "99+" : count}</span>; }
function State({ icon, title, description, children }: { icon: ReactNode; title: string; description?: string; children?: ReactNode }) { return <div className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-slate-500">{icon}</div><h3 className="mt-4 font-semibold text-slate-950">{title}</h3>{description && <p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">{description}</p>}{children && <div className="mt-5">{children}</div>}</div>; }
export const EmptyState = ({ title = "Nothing here yet", description, children }: Omit<Parameters<typeof State>[0], "icon">) => <State icon={<Info className="h-5 w-5" />} title={title} description={description}>{children}</State>;
export const ErrorState = ({ title = "Something went wrong", description, children }: Omit<Parameters<typeof State>[0], "icon">) => <State icon={<AlertCircle className="h-5 w-5" />} title={title} description={description}>{children}</State>;
export const SuccessState = ({ title = "Success", description, children }: Omit<Parameters<typeof State>[0], "icon">) => <State icon={<CheckCircle2 className="h-5 w-5" />} title={title} description={description}>{children}</State>;
export const NoResults = ({ description, children }: { description?: string; children?: ReactNode }) => <EmptyState title="No results found" description={description}>{children}</EmptyState>;
export const OfflineState = ({ description, children }: { description?: string; children?: ReactNode }) => <State icon={<WifiOff className="h-5 w-5" />} title="You’re offline" description={description}>{children}</State>;
export const MaintenanceState = ({ description, children }: { description?: string; children?: ReactNode }) => <State icon={<Wrench className="h-5 w-5" />} title="Under maintenance" description={description}>{children}</State>;
