"use client";

import type { ButtonHTMLAttributes, ReactNode } from "react";
import { X } from "lucide-react";
import { cn } from "@lib/utils";
import { Button } from "./Button";

type OverlayProps = { open: boolean; onClose?: () => void; title: string; description?: string; children: ReactNode; className?: string };
function CloseButton({ onClose }: { onClose?: () => void }) { return onClose ? <Button variant="ghost" size="icon" aria-label="Close" onClick={onClose}><X className="h-5 w-5" /></Button> : null; }
export function Modal({ open, onClose, title, description, children, className }: OverlayProps) { if (!open) return null; return <div className="fixed inset-0 z-[60] flex items-center justify-center p-4" role="presentation"><button aria-label="Close dialog" className="absolute inset-0 cursor-default bg-slate-950/50" onClick={onClose} /><section role="dialog" aria-modal="true" aria-labelledby="modal-title" className={cn("relative z-10 w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl", className)}><div className="flex items-start justify-between gap-4"><div><h2 id="modal-title" className="text-xl font-semibold text-slate-950">{title}</h2>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}</div><CloseButton onClose={onClose} /></div><div className="mt-6">{children}</div></section></div>; }
export function Drawer({ open, onClose, title, description, children, className }: OverlayProps) { if (!open) return null; return <div className="fixed inset-0 z-[60]" role="presentation"><button aria-label="Close drawer" className="absolute inset-0 cursor-default bg-slate-950/50" onClick={onClose} /><aside role="dialog" aria-modal="true" aria-labelledby="drawer-title" className={cn("absolute inset-y-0 right-0 flex w-full max-w-md flex-col bg-white p-6 shadow-2xl", className)}><div className="flex items-start justify-between gap-4"><div><h2 id="drawer-title" className="text-xl font-semibold text-slate-950">{title}</h2>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}</div><CloseButton onClose={onClose} /></div><div className="mt-6 flex-1 overflow-y-auto">{children}</div></aside></div>; }
export const SidePanel = Drawer;
export function BottomSheet({ open, onClose, title, description, children, className }: OverlayProps) { if (!open) return null; return <div className="fixed inset-0 z-[60]" role="presentation"><button aria-label="Close sheet" className="absolute inset-0 cursor-default bg-slate-950/50" onClick={onClose} /><section role="dialog" aria-modal="true" aria-labelledby="sheet-title" className={cn("absolute inset-x-0 bottom-0 max-h-[85vh] overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl", className)}><div className="mx-auto h-1.5 w-12 rounded-full bg-slate-300" /><div className="mt-5 flex items-start justify-between gap-4"><div><h2 id="sheet-title" className="text-xl font-semibold text-slate-950">{title}</h2>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}</div><CloseButton onClose={onClose} /></div><div className="mt-6">{children}</div></section></div>; }
export function ConfirmationDialog({ confirmLabel = "Confirm", cancelLabel = "Cancel", onConfirm, onClose, ...props }: OverlayProps & { confirmLabel?: string; cancelLabel?: string; onConfirm: ButtonHTMLAttributes<HTMLButtonElement>["onClick"] }) { return <Modal {...props} onClose={onClose}><div className="flex justify-end gap-3"><Button variant="outline" onClick={onClose}>{cancelLabel}</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></div></Modal>; }
export function AlertDialog({ buttonLabel = "Continue", onClose, ...props }: OverlayProps & { buttonLabel?: string }) { return <Modal {...props} onClose={onClose}><div className="flex justify-end"><Button onClick={onClose}>{buttonLabel}</Button></div></Modal>; }
export const FutureWizard = Modal;
